version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      VMCXcJQBRAd6rpTmIWWg6/ghJgEqiNdCMyG2vINtw3YD6ZzGiRf32ihYilc9nCsEtkJZySXAiEuaUdrQTBkC3SItGz83PDrFfLrEE7x7M2isOig06HlL/D+CaDSRnzyUFMQAy7/bWrwzPlbcWwRPMyQzb5zfzdt3TnGOp5lzof8HcVDePDf8ZN9sPzJAewuTyrgOrm2Ch67vIJAS1y9tXnMJe9dq+RyWt83qeZ1s45QKgkakSW3QZQnyVWOQTyqdPrrzkKcADFNx04xf/c522b/4LabHxSeTgf+caQnaNzApam0Tk+emNC0dj/0JcPdQjFJl/siPTyb/ae4JOWDhOm+5Wv7ZqINyt+NT7a8f98lU4QyS7xWDBf80q+kne7ge7gXa3WDZFVJg9HhzhZamrfxdy1znrnQhbSjWvqeo8LkAb7skhiStPL8qNaB7oGQOJ1DoDMZYQaM5OC4W+Yv1eVS7MC7cHdbeLazWdJGcSoX9dA5kklQX6c1B0NXvrtBk3Ehsdv9Ph3DJEC64l+K7JxMpErP9mAeiH1mkXefWtFaWGaU4UZOmOYjJU1jut9X7rjWAzrfJk2gSaNm+ahaCTUMZs12PzEfrEHxX5TMZ4LNYojrFL6Gi4WQTVEiLb9O4csbM/SmHZFl9jgaeSs7Z5xA0MqhFpHbJN6u/On4bPAs=
