version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      DQ7iqp1X4ImRiDUQjnPRxLqNaJAhlNDdZ+caaD777p7UVS1KJke8e0z3HX+YLzEG6/tGLrogoFLG8ayfb7/9d9z+eZSRGdAR3UHmsSnZHc7sMNYf26fZX0XtDKdSEB+hw6v8ZF80CdBv7AVwH/UpazTr5yW3jy8gzWpiz/hRMJ6MDixYPfrBlHZCf7nHMkpiuyBUQSexcElUYracDNR1TCMOUgPdchpgT0ddmKdRn5SPHTIPIC6oSwWLgf1Wx0STzxKkm6h1H5Vam2qazDqBs5tHncjmq1QoBqJdVYB+qQcXxJGJ8MDDYVACI/Bxr0SPaUab/7BcHsaUPHrOyiHj1A5atiPbM+C59F8xArB5yJVThgXexUVE/15UJMm54mgy18vnkewoM2SDBbdp229dhV+d6ioJHSSYixD5jX2tskXmHuw210B4BkXTA+J7f+89SH9ayinx0BE26tG3UEQbYnb3A5+R41y/69zTE92j2WbwGMiHsk3TrXgvyUQeLXVaMhqILTD862y/BJq+4fXy6f7/7FTAAHOA8VPh4XZswgOGFhLq7T8uDw6hKqqHUlpAxCJJvXCr1Ubh6UvUCp8liEpGlH3ZDCBJM9kZZtyHQ1d9GF9gs/ChwMBS4xY+iP6RdZ9z3O7ErhFgm6daId+5TmEavqZ0qgltT0imsofy71k=
